factory = Factory.create(name:"CPF")
factory2 = Factory.create(name:"KFC")

department1 = Department.create(name:"KFC", factory_id: factory.id)
department2 = Department.create(name:"CFK", factory_id: factory.id)

department3 = Department.create(name:"MK", factory_id: factory2.id)
department4 = Department.create(name:"Yayoi", factory_id: factory2.id)

department5 = Department.create(name:"Yayoi", factory_id: factory.id)
department6 = Department.create(name:"Yayoi", factory_id: factory.id)
department7 = Department.create(name:"Yayoi", factory_id: factory.id)
department8 = Department.create(name:"Yayoi", factory_id: factory.id)
department9 = Department.create(name:"Yayoi", factory_id: factory.id)
department10 = Department.create(name:"Yayoi", factory_id: factory.id)
department11 = Department.create(name:"Yayoi", factory_id: factory.id)
department12 = Department.create(name:"Yayoi", factory_id: factory.id)
department13 = Department.create(name:"Yayoi", factory_id: factory.id)
department14 = Department.create(name:"Yayoi", factory_id: factory.id)
department15 = Department.create(name:"Yayoi", factory_id: factory.id)
department16 = Department.create(name:"Yayoi", factory_id: factory.id)
department17 = Department.create(name:"Yayoi", factory_id: factory.id)
department18 = Department.create(name:"Yayoi", factory_id: factory.id)
department19 = Department.create(name:"Yayoi", factory_id: factory.id)
department20 = Department.create(name:"Yayoi", factory_id: factory.id)
department21 = Department.create(name:"Yayoi", factory_id: factory.id)
department22 = Department.create(name:"Yayoi", factory_id: factory.id)


user0= Account.create(name: "แอดมิน", username: "admin", password: "1", factory_id: factory.id, role: "Admin")

user1= Account.create(name: "ผู้จัดการ1", username: "manager1", password: "1", factory_id: factory.id, role: "Manager")
user2= Account.create(name: "ผู้จัดการ2", username: "manager2", password: "1", factory_id: factory.id, role: "Manager")

user3= Account.create(name: "พนักงาน1 ข้อมูลตัวอย่าง", username: "Worker1", password: "1", factory_id: factory.id, role: "Worker")
user4= Account.create(name: "พนักงาน2 ข้อมูลตัวอย่าง", username: "Worker2", password: "1", factory_id: factory.id, role: "Worker")
user5= Account.create(name: "พนักงาน3 ข้อมูลตัวอย่าง", username: "Worker3", password: "1", factory_id: factory.id, role: "Worker")
user6= Account.create(name: "พนักงาน4 ข้อมูลตัวอย่าง", username: "Worker4", password: "1", factory_id: factory.id, role: "Worker")
user7= Account.create(name: "พนักงาน5 ข้อมูลตัวอย่าง", username: "Worker5", password: "1", factory_id: factory.id, role: "Worker")
user8= Account.create(name: "พนักงาน6 ข้อมูลตัวอย่าง", username: "Worker6", password: "1", factory_id: factory.id, role: "Worker")
user9= Account.create(name: "พนักงาน7 ข้อมูลตัวอย่าง", username: "Worker7", password: "1", factory_id: factory.id, role: "Worker")
user10= Account.create(name: "พนักงาน8 ข้อมูลตัวอย่าง", username: "Worker8", password: "1", factory_id: factory.id, role: "Worker")
user11= Account.create(name: "พนักงาน9 ข้อมูลตัวอย่าง", username: "Worker9", password: "1", factory_id: factory.id, role: "Worker")
user12= Account.create(name: "พนักงาน10 ข้อมูลตัวอย่าง", username: "Worker10", password: "1", factory_id: factory.id, role: "Worker")

user13= Account.create(name: "สมชาย ร้อยเสน่ห์ ", username: "Worker11", password: "1", factory_id: factory.id, role: "Worker")
user14= Account.create(name: "มหาเวทย์ ผนึกมาร ", username: "Worker12", password: "1", factory_id: factory.id, role: "Worker")
user15= Account.create(name: "จัตุรงค์ บรรจงยิง", username: "Worker13", password: "1", factory_id: factory.id, role: "Worker")
user16= Account.create(name: "รรรรร เทพจริง ", username: "Worker14", password: "1", factory_id: factory.id, role: "Worker")
user17= Account.create(name: "มหาหล่อ บางกระดี้ดี ", username: "Worker15", password: "1", factory_id: factory.id, role: "Worker")
user18= Account.create(name: "เฟรนส์ โซนส์ ", username: "Worker16", password: "1", factory_id: factory.id, role: "Worker")
user19= Account.create(name: "มานะ หนึ่งเดียว  ", username: "Worker17", password: "1", factory_id: factory.id, role: "Worker")
user20= Account.create(name: "มานะ ใจสลาย", username: "Worker18", password: "1", factory_id: factory.id, role: "Worker")


task1 = Task.create(account_id: user3.id, department_id: department1.id, day: Time.parse('23-11-2021'), shift: "1", ot: 2, startTime: Time.now, active: true)
task2 = Task.create(account_id: user3.id, department_id: department1.id, day: Time.parse('24-11-2021'), shift: "1", ot: 2, startTime: Time.now, active: true)
task3 = Task.create(account_id: user3.id, department_id: department1.id, day: Time.parse('25-11-2021'), shift: "1", ot: 2, startTime: Time.now, active: true)

task4 = Task.create(account_id: user3.id, department_id: department2.id, day: Time.parse('22-11-2021'), shift: "1", ot: 2, startTime: Time.now, active: false)
task5 = Task.create(account_id: user3.id, department_id: department2.id, day: Time.parse('23-11-2021'), shift: "1", ot: 2, startTime: Time.now, active: false)
task6 = Task.create(account_id: user3.id, department_id: department2.id, day: Time.parse('24-11-2021'), shift: "1", ot: 2, startTime: Time.now, active: false)
task7 = Task.create(account_id: user3.id, department_id: department2.id, day: Time.parse('25-11-2021'), shift: "1", ot: 2, startTime: Time.now, active: false)

task8 = Task.create(account_id: user5.id, department_id: department1.id, day: Time.parse('22-11-2021'), shift: "1", ot: 2, startTime: Time.now, active: true)
task9 = Task.create(account_id: user5.id, department_id: department1.id, day: Time.parse('23-11-2021'), shift: "1", ot: 2, startTime: Time.now, active: true)
task10 = Task.create(account_id: user5.id, department_id: department1.id, day: Time.parse('24-11-2021'), shift: "1", ot: 2, startTime: Time.now, active: true)
task11 = Task.create(account_id: user5.id, department_id: department1.id, day: Time.parse('25-11-2021'), shift: "1", ot: 2, startTime: Time.now, active: true)

task12 = Task.create(account_id: user6.id, department_id: department2.id, day: Time.parse('22-11-2021'), shift: "1", ot: 2, startTime: Time.now, active: false)
task13 = Task.create(account_id: user6.id, department_id: department2.id, day: Time.parse('23-11-2021'), shift: "1", ot: 2, startTime: Time.now, active: false)
task14 = Task.create(account_id: user6.id, department_id: department2.id, day: Time.parse('24-11-2021'), shift: "1", ot: 2, startTime: Time.now, active: false)
task15 = Task.create(account_id: user6.id, department_id: department2.id, day: Time.parse('25-11-2021'), shift: "1", ot: 2, startTime: Time.now, active: false)

task16 = Task.create(account_id: user7.id, department_id: department1.id, day: Time.parse('24-11-2021'), shift: "1", ot: 4, startTime: Time.now, active: true)
task17 = Task.create(account_id: user8.id, department_id: department2.id, day: Time.parse('24-11-2021'), shift: "1", ot: 4, startTime: Time.now, active: false)
task18 = Task.create(account_id: user9.id, department_id: department1.id, day: Time.parse('25-11-2021'), shift: "1", ot: 4, startTime: Time.now, active: true)
task19 = Task.create(account_id: user10.id, department_id: department2.id, day: Time.parse('25-11-2021'), shift: "1", ot: 4, startTime: Time.now, active: false)

task20 = Task.create(account_id: user11.id, department_id: department1.id, day: Time.parse('24-11-2021'), shift: "2", ot: 2, startTime: Time.now, active: true)
task21 = Task.create(account_id: user12.id, department_id: department1.id, day: Time.parse('25-11-2021'), shift: "2", ot: 2, startTime: Time.now, active: false)
task22 = Task.create(account_id: user13.id, department_id: department2.id, day: Time.parse('24-11-2021'), shift: "2", ot: 2, startTime: Time.now, active: true)
task23 = Task.create(account_id: user14.id, department_id: department2.id, day: Time.parse('25-11-2021'), shift: "2", ot: 2, startTime: Time.now, active: false)

task24 = Task.create(account_id: user15.id, department_id: department1.id, day: Time.parse('26-11-2021'), shift: "2", ot: 0, startTime: Time.now, active: true)
task25 = Task.create(account_id: user16.id, department_id: department1.id, day: Time.parse('26-11-2021'), shift: "2", ot: 0, startTime: Time.now, active: false)
task26 = Task.create(account_id: user17.id, department_id: department2.id, day: Time.parse('26-11-2021'), shift: "2", ot: 0, startTime: Time.now, active: true)
task27 = Task.create(account_id: user18.id, department_id: department2.id, day: Time.parse('26-11-2021'), shift: "2", ot: 0, startTime: Time.now, active: false)
