factory = Factory.create(name:"CPF")
factory2 = Factory.create(name:"KFC")

department1 = Department.create(name:"KFC", factory_id: factory.id)
department2 = Department.create(name:"CFK", factory_id: factory.id)

department3 = Department.create(name:"MK", factory_id: factory2.id)
department4 = Department.create(name:"Yayoi", factory_id: factory2.id)
admin= Account.create(name: "แอดมิน", username: "admin", password: "1", factory_id: factory.id, role: "Admin")
mana1= Account.create(name: "ผู้จัดการ1", username: "manager1", password: "1", factory_id: factory.id, role: "Manager")
mana2= Account.create(name: "ผู้จัดการ2", username: "manager2", password: "1", factory_id: factory.id, role: "Manager")

user1= Account.create(name: "พนักงาน1 ข้อมูลตัวอย่าง", username: "Worker1", password: "1", factory_id: factory.id, role: "Worker", detail: {"telephone":"092-548-5697"})
user2= Account.create(name: "พนักงาน2 ข้อมูลตัวอย่าง", username: "Worker2", password: "1", factory_id: factory.id, role: "Worker", detail: {"telephone":"092-578-5697"})
user3= Account.create(name: "พนักงาน3 ข้อมูลตัวอย่าง", username: "Worker3", password: "1", factory_id: factory.id, role: "Worker", detail: {"telephone":"092-548-6897"})
user4= Account.create(name: "พนักงาน4 ข้อมูลตัวอย่าง", username: "Worker4", password: "1", factory_id: factory.id, role: "Worker", detail: {"telephone":"095-548-5897"})
user5= Account.create(name: "พนักงาน5 ข้อมูลตัวอย่าง", username: "Worker5", password: "1", factory_id: factory.id, role: "Worker", detail: {"telephone":"097-983-5697"})
user6= Account.create(name: "พนักงาน6 ข้อมูลตัวอย่าง", username: "Worker6", password: "1", factory_id: factory.id, role: "Worker", detail: {"telephone":"091-685-3321"})
user7= Account.create(name: "พนักงาน7 ข้อมูลตัวอย่าง", username: "Worker7", password: "1", factory_id: factory.id, role: "Worker", detail: {"telephone":"091-234-5678"})
user8= Account.create(name: "พนักงาน8 ข้อมูลตัวอย่าง", username: "Worker8", password: "1", factory_id: factory.id, role: "Worker", detail: {"telephone":"095-678-9101"})
user9= Account.create(name: "พนักงาน9 ข้อมูลตัวอย่าง", username: "Worker9", password: "1", factory_id: factory.id, role: "Worker", detail: {"telephone":"093-458-5577"})
user10= Account.create(name: "พนักงาน10 ข้อมูลตัวอย่าง", username: "Worker10", password: "1", factory_id: factory.id, role: "Worker", detail: {"telephone":"094-358-4579"})


user11= Account.create(name: "สมชาย ร้อยเสน่ห์ ", username: "Worker11", password: "1", factory_id: factory.id, role: "Worker", detail: {"telephone":"082-528-5123"})
user12= Account.create(name: "มหาเวทย์ ผนึกมาร ", username: "Worker12", password: "1", factory_id: factory.id, role: "Worker", detail: {"telephone":"092-538-2588"})
user13= Account.create(name: "จัตุรงค์ บรรจงยิง", username: "Worker13", password: "1", factory_id: factory.id, role: "Worker", detail: {"telephone":"090-500-4258"})
user14= Account.create(name: "รรรรร เทพจริง ", username: "Worker14", password: "1", factory_id: factory.id, role: "Worker", detail: {"telephone":"091-485-7589"})
user15= Account.create(name: "มหาหล่อ บางกระดี้ดี ", username: "Worker15", password: "1", factory_id: factory.id, role: "Worker", detail: {"telephone":"062-123-0468"})
user16= Account.create(name: "เฟรนส์ โซนส์", username: "Worker16", password: "1", factory_id: factory.id, role: "Worker", detail: {"telephone":"0XX-XXX-XXXX"})
user17= Account.create(name: "มานะ หนึ่งเดียว ", username: "Worker17", password: "1", factory_id: factory.id, role: "Worker", detail: {"telephone":"0XX-XXX-XXXX"})
user18= Account.create(name: "เควิน แฟรงกี", username: "Worker18", password: "1", factory_id: factory.id, role: "Worker", detail: {"telephone":"0XX-XXX-XXXX"})
user19= Account.create(name: "เบน เทน", username: "Worker19", password: "1", factory_id: factory.id, role: "Worker", detail: {"telephone":"0XX-XXX-XXXX"})
user20= Account.create(name: "ภาคภูมิ ปูนปั้น", username: "Worker20", password: "1", factory_id: factory.id, role: "Worker", detail: {"telephone":"0XX-XXX-XXXX"})
user21= Account.create(name: "ชาญชนก สุวรรณมณีรัตนะ", username: "Worker21", password: "1", factory_id: factory.id, role: "Worker", detail: {"telephone":"0XX-XXX-XXXX"})
user22= Account.create(name: "กรวีร์ สมยศ", username: "Worker22", password: "1", factory_id: factory.id, role: "Worker", detail: {"telephone":"0XX-XXX-XXXX"})
user24= Account.create(name: "ภาภูมิโตะ ปูปะโตะ", username: "Worker24", password: "1", factory_id: factory.id, role: "Worker", detail: {"telephone":"0XX-XXX-XXXX"})
user25= Account.create(name: "สมบัติ วันพีช", username: "Worker25", password: "1", factory_id: factory.id, role: "Worker", detail: {"telephone":"0XX-XXX-XXXX"})

user26= Account.create(name: "สมชาย รักดี", username: "Worker26", password: "1", factory_id: factory.id, role: "Worker", detail: {"telephone":"0XX-XXX-XXXX"})
user27= Account.create(name: "สมบูรณ์ ซีอิ้วขาว", username: "Worker27", password: "1", factory_id: factory.id, role: "Worker", detail: {"telephone":"0XX-XXX-XXXX"})
user28= Account.create(name: "อาหลิว เต๋อหัว", username: "Worker28", password: "1", factory_id: factory.id, role: "Worker", detail: {"telephone":"0XX-XXX-XXXX"})
user29= Account.create(name: "นงรัก ไม่รัก", username: "Worker29", password: "1", factory_id: factory.id, role: "Woker", detail: {"telephone":"0XX-XXX-XXXX"})
user30= Account.create(name: "จอร์น หมั่นเพียร", username: "Worker30", password: "1", factory_id: factory.id, role: "Worker", detail: {"telephone":"0XX-XXX-XXXX"})
user31= Account.create(name: "เจซสิก้า ปากหาร", username: "Worker31", password: "1", factory_id: factory.id, role: "Worker", detail: {"telephone":"0XX-XXX-XXXX"})
user32= Account.create(name: "สมหวัง ชายโสด", username: "Worker32", password: "1", factory_id: factory.id, role: "Worker", detail: {"telephone":"0XX-XXX-XXXX"})
user33= Account.create(name: "อนามัย อนามุย", username: "Worker33", password: "1", factory_id: factory.id, role: "Worker", detail: {"telephone":"0XX-XXX-XXXX"})
user34= Account.create(name: "หมูหัน พันแล๋ป", username: "Worker34", password: "1", factory_id: factory.id, role: "Worker", detail: {"telephone":"0XX-XXX-XXXX"})
user35= Account.create(name: "แดง หลังอาน", username: "Worker35", password: "1", factory_id: factory.id, role: "Worker", detail: {"telephone":"0XX-XXX-XXXX"})
user36= Account.create(name: "เขียว รักพืซ", username: "Worker36", password: "1", factory_id: factory.id, role: "Worker", detail: {"telephone":"0XX-XXX-XXXX"})
user37= Account.create(name: "เชอรี่ สามโคก", username: "Worker37", password: "1", factory_id: factory.id, role: "Woker", detail: {"telephone":"0XX-XXX-XXXX"})
user38= Account.create(name: "ตี้กแตน ชนแล้วด่า", username: "Worker38", password: "1", factory_id: factory.id, role: "Worker", detail: {"telephone":"0XX-XXX-XXXX"})
user39= Account.create(name: "พิเชต บุรุตวิทย์", username: "Worker39", password: "1", factory_id: factory.id, role: "Worker", detail: {"telephone":"0XX-XXX-XXXX"})

